# DO NOT EDIT - This file is automatically generated
# Make changes to Manifest.txt and/or Rakefile and regenerate
# -*- encoding: utf-8 -*-
# stub: thin_search 0.4.2 ruby lib

Gem::Specification.new do |s|
  s.name = "thin_search"
  s.version = "0.4.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["Jeremy Hinegardner", "Ara T. Howard"]
  s.date = "2015-12-12"
  s.description = "Thin Search aims to be the easiest way to add full text search to your Ruby application. Any object may be indexed and become searchable."
  s.email = ["jeremy@copiousfreetime.org", "ara.t.howard@gmail.com"]
  s.extra_rdoc_files = ["CONTRIBUTING.md", "HISTORY.md", "Manifest.txt", "README.md"]
  s.files = ["CONTRIBUTING.md", "HISTORY.md", "LICENSE", "Manifest.txt", "README.md", "Rakefile", "lib/thin_search.rb", "tasks/default.rake", "tasks/this.rb", "test/test_helper.rb", "test/test_version.rb"]
  s.homepage = "http://github.com/copiousfreetime/thin_search"
  s.licenses = ["MIT"]
  s.rdoc_options = ["--main", "README.md", "--markup", "tomdoc"]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.3")
  s.rubygems_version = "2.4.8"
  s.summary = "Thin Search aims to be the easiest way to add full text search to your Ruby application. Any object may be indexed and become searchable."

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<amalgalite>, ["~> 1.5"])
      s.add_development_dependency(%q<rake>, ["~> 10.3"])
      s.add_development_dependency(%q<minitest>, ["~> 5.7"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_development_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_development_dependency(%q<faker>, ["~> 1.5"])
    else
      s.add_dependency(%q<amalgalite>, ["~> 1.5"])
      s.add_dependency(%q<rake>, ["~> 10.3"])
      s.add_dependency(%q<minitest>, ["~> 5.7"])
      s.add_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_dependency(%q<simplecov>, ["~> 0.10"])
      s.add_dependency(%q<faker>, ["~> 1.5"])
    end
  else
    s.add_dependency(%q<amalgalite>, ["~> 1.5"])
    s.add_dependency(%q<rake>, ["~> 10.3"])
    s.add_dependency(%q<minitest>, ["~> 5.7"])
    s.add_dependency(%q<rdoc>, ["~> 4.1"])
    s.add_dependency(%q<simplecov>, ["~> 0.10"])
    s.add_dependency(%q<faker>, ["~> 1.5"])
  end
end
